version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: listen
    versions:
    - 3.5.0
  - dependency-name: webmock
    versions:
    - 3.11.2
    - 3.11.3
    - 3.12.0
    - 3.12.1
  - dependency-name: rails
    versions:
    - 6.1.1
    - 6.1.2
    - 6.1.2.1
    - 6.1.3

- package-ecosystem: "docker"
  directory: "/"
  schedule:
    interval: "daily"
    time: "03:00"
  open-pull-requests-limit: 10
  # Set update schedule for GitHub Actions

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    # Check for updates to GitHub Actions every week
    interval: "weekly"
