name: release-re-request-an-aws-account

on:
  push:
    branches: [ main ]

  workflow_dispatch:
jobs:
  build-release:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
      - name: add-cloudfoundry-repository
        run: |
          wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
          echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list


      - name: deploy-redirect
        env:
          CF_USERNAME: ${{ secrets.CF_EMAIL }}
          CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
        run: |
          cf api https://api.cloud.service.gov.uk 
          cf auth
          cf target -o gds-tech-ops -s re-aws-account-management
          cf push -f ./raat-redirect/manifest.yml --strategy rolling
