name: Run tests and deploy on merge to main

on:
  push:
    branches:
      - 'main'

jobs:
  run-tests: 
    uses: alphagov/re-request-an-aws-account/.github/workflows/rubyandnode.yaml@main
  publish-docker-image: 
    uses: alphagov/re-request-an-aws-account/.github/workflows/ghcr.yml@main
