name: Run tests and deploy on merge to main

on:
  push:
    branches:
      - 'main'

permissions:
  contents: read
  packages: write

jobs:
  run-tests: 
    uses: alphagov/re-request-an-aws-account/.github/workflows/rubyandnode.yaml@main
  publish-docker-image: 
    needs: run-tests
    uses: alphagov/re-request-an-aws-account/.github/workflows/ghcr.yml@main
    secrets: inherit
