name: Run tests
permissions:
  contents: read

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 #v6.0.3

    - name: Get ruby version from '.ruby-version' file
      id: ruby-version
      run: echo "version=$(cat .ruby-version)" >> $GITHUB_OUTPUT

    - name: Set up Ruby
      uses: ruby/setup-ruby@89f90524b88a01fe6e0b732220432cc6142926af #v1.313.0
      with:
        ruby-version: ${{ steps.ruby-version.outputs.version }}

    - name: Get node version from '.node-version' file
      id: node-version
      run: echo "version=$(cat .node-version)" >> $GITHUB_OUTPUT
        
    - name: Set up Node
      uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 #v7.0.0
      with:
        node-version: ${{ steps.node-version.outputs.version }}

    - name: Install bundler packages
      run: bundle install --without development

    - name: Install node packages
      run: npm ci
    
    - name: Test application
      run: bundle exec rake
